### ISSUE TITLE
Where is the raw dataset?

### ISSUE THREAD

**Issue by henrywoo** [Vul-LMGNN/vul-LMGGNN#1]
I was following the `Preparing the CPG` command but got issue below:

`FileNotFoundError: File data/raw/dataset.json does not exist`

May I know where is the raw `dataset.json`?

**Comment by Vul-LMGNN** [comment]
Hi henrywoo, you can find the corresponding dataset via this link: https://drive.google.com/file/d/1x6hoF7G-tSYxg8AFybggypLZgMGDNHfF/view. Please note that you may need to slightly modify the code for extracting CPG based on the format of different datasets.
