### ISSUE TITLE
Version Of Joern

### ISSUE THREAD

**Issue by initialWu** [Vul-LMGNN/vul-LMGGNN#3]
Thanks for your work! I want to get an example of CPG, but when I tried to use your function:
``` 
cpg_file = process.joern_parse(joern_cli_dir, input_path, output_path, cpg_fname)
json_files = process.joern_create(joern_cli_dir, output_path, json_out, ['test_0.bin'])
```
I got the following output:
![image](https://github.com/Vul-LMGNN/vul-LMGGNN/assets/67249255/43a70b86-069e-4ba4-a2d0-8928269cab75)

Then I used your process command `cpg.runScript` in function `joern_create` of `utils/process/cpg_generator.py` in joern terminal, but I got this error:
![image](https://github.com/Vul-LMGNN/vul-LMGGNN/assets/67249255/150a603d-ec90-4ccc-b102-6fa798869f9d)

So I don't think I have the **same version** of Joern installed as yours. Can you please tell me which version you are using? 
The Joern I installed is **Version: 2.0.357**. The Joern document gives instruction of implementing scripts like [This](https://docs.joern.io/interpreter/#basic-usage). So I tried to modify your `graph-for-funcs.sc` scripts, and added a cpgFile parameter(path of bin file obtained by joern-parse) and an importCpg call(following Joern Document) like :
```
@main def main(cpgFile: String): Json = {
  importCpg(cpgFile)
  GraphForFuncsResult(
```
But then I got more errors. 
![image](https://github.com/Vul-LMGNN/vul-LMGGNN/assets/67249255/2ae2271b-932f-4a7d-86a4-4418a666b6d0)
Could you please give me some help? Thanks.

**Comment by YunFy26** [comment]
@initialWu Hello, When I used `cpg.runScript`, I get the same error.
The Joern I installed is **Version: 2.0.401**
I'd like to know if you've solved this problem, and I'd be very grateful if you could give me a reply.

**Comment by initialWu** [comment]
> @initialWu Hello, When I used `cpg.runScript`, I get the same error. The Joern I installed is **Version: 2.0.401** I'd like to know if you've solved this problem, and I'd be very grateful if you could give me a reply.

The new version of Joern no longer supports cpg.runScript. I resolved this issue by directly running joern-cli with the `--script` parameter, following the methods described in [Joern’s documentation](https://docs.joern.io/interpreter/). The provided scripts in the repository might require modifications in new version.

**Comment by ChenglinW** [comment]
I've got the same error after running the script, it might be caused by the absence of io.circe in scala3. Have you resolved the issue?

**Comment by ChenglinW** [comment]
I have resolved the issue by rewriting the script and rebuilding the joern, the problem is caused by lacking certain scala packages

**Comment by ckj18** [comment]
Could you share the modified script?

**Comment by Abdelrahman-405** [comment]
@ChenglinW can you provide the new script, plz?

**Comment by Abdelrahman-405** [comment]
> I have resolved the issue by rewriting the script and rebuilding the joern, the problem is caused by lacking certain scala packages

Can you help me to solve this problem please
