### ISSUE TITLE
Clarification Needed: JDK, Scala, SBT Versions, and build.sbt File

### ISSUE THREAD

**Issue by Abdelrahman-405** [Vul-LMGNN/vul-LMGGNN#8]
Hello,  

Thank you for sharing this project! I am trying to run it but encountered some challenges due to version mismatches. Could you please specify the following details to help me set up the environment correctly?  

1. The Java Development Kit (JDK) version used.  
2. The Scala version required.  
3. The SBT version used for building the project.  
4. A copy or example of the `build.sbt` file (if not already included).  

This information would be immensely helpful in resolving setup issues and successfully running the project.  

Thank you in advance for your support!

**Comment by huangyuyan3** [comment]
> Hello,
> 
> Thank you for sharing this project! I am trying to run it but encountered some challenges due to version mismatches. Could you please specify the following details to help me set up the environment correctly?
> 
> 1. The Java Development Kit (JDK) version used.
> 2. The Scala version required.
> 3. The SBT version used for building the project.
> 4. A copy or example of the  file (if not already included).`build.sbt`
> 
> This information would be immensely helpful in resolving setup issues and successfully running the project.
> 
> Thank you in advance for your support!

May I ask if you have successfully reproduced it?
